CREATE TABLE `FREEBOARD_TB` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(45) NOT NULL,
  `USERID` varchar(45) NOT NULL,
  `CONTENT` text,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `REQUESTCODEINFO_TB` (
  `REQUESTCODE` varchar(20) NOT NULL,
  `CODEEXPLAIN` varchar(45) NOT NULL,
  PRIMARY KEY (`REQUESTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `REQUESTHISTORY_TB` (
  `REQUESTCODE` varchar(20) DEFAULT NULL,
  `USERID` varchar(45) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TEAMINFO_TB` (
  `TEAMCODE` varchar(20) NOT NULL,
  `TEAMNAME` varchar(45) NOT NULL,
  PRIMARY KEY (`TEAMCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USERINFO_TB` (
  `USERID` varchar(45) NOT NULL,
  `USERNAME` varchar(45) DEFAULT NULL,
  `TEAMCODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
